name: e2e-test-action
run-name: ${{ github.actor }} e2e test GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      valkey:
        image: valkey/valkey:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "valkey-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Valkey
        run:  |
          sudo apt update && sudo apt-get install valkey -y
          echo "ACL SETUSER redis on >password ~* +@all" | valkey-cli
          echo "ACL LIST" | valkey-cli
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install go module
        run: go mod download
      - name: Build app
        run: go build -o main ./main.go
      - name: start app
        run: ./main &
        env:
          DB_HOST: localhost #ランナーマシン上での実行 https://docs.github.com/ja/actions/using-containerized-services/about-service-containers#running-jobs-on-the-runner-machine
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: password
          DB_NAME: postgres
          CACHE_DB_HOST: localhost
          CACHE_DB_PORT: 6379
          CACHE_DB_USER: redis
          CACHE_DB_PASS: password          
      - name: Install runn
        run: go install github.com/k1LoW/runn/cmd/runn@latest
      - name: Exec test
        run: runn run runn.yaml
