name: e2e-test -ction
run-name: ${{ github.actor }} e2e test GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install go module
        run: go mod download
      - name: Build app
        run: go build -o main ./main.go
      - name: start app
        run: ./main &
      - name: Install runn
        run: go install github.com/k1LoW/runn/cmd/runn@latest
      - name: Exec test
        run: runn run runn.yaml
